### pin_mask demo
- We get a $1^{st}$ embedding (using random init)
- linearly transform so "good" and "bad" samples so their x values end up at [-1,+1]
    - (in least-squares sense)
- then re-embed "pinning" those x values *exactly* at -1, +1
    - (could random-init by-hand, then fix x values for single pin_mask umap fit)
- umap applies no gradient (but does apply rescaling)
- we determine the new linear rescaling
- and remap the embedding back to good|bad x-values -1|+1

### New
- We select a good/bad entry based on feature 0 "sepal length"
  for each iris species.  Lowest pinned to x=-1, highest pinned to x=+1
  
  
- still perhaps better to ROTATE (see Kabsch algorithm) the initial embedding
  such that good|bad points are aligned *towards* (-1,0)|(+1,0) idealized drag
  positions
   - then rescale and shift to put their x-centroids exactly at (-1,0)|(+1,0)
- Now we rotate, scale & shift
- TODO: option to **shear** instead of orthogonally rotate

#### behavior is not (completely) *as expected*!
- Still no *constraint* of having unpinned points having x-values between (-1,+1)

### New
- added a 'TRIAL' code blocks into layouts.py to test dimension-wise clipping bound
- clipping bounds for *x* must be -10,+10 so that spectral init is not fubar.
- *GOOD*: final embedding now does have *unpinned points* "on the inside"

### NEW: add hover tool to inspect bokeh embedding (and data) values

### *TODO*: add a user-passible `constraint` object (default=None) to UMAP.
- or actually, a list of constraint objects
- `constraint.project_onto_constraint( low_embedding_vector )` may do an
  in-place modification of `low_embedding_vector`
- layouts.py has a `jitclass` called `DimLohi` example of a clipping constraint
- other constraint types might project the full data set (during/post-epoch?),
  perhaps like `DimLoHi:project_rows_onto_constraint(self, mat)`
  
### *LATER*: see if UMAP can crudely be simulated by spring & dashpot physics
- *springs* : equilibrium distances and force constants
- *dashpots* : motion damping proportional to velocity

Why? such force fields can be quickly done client side, all in the low-dim embedding space.

Init via nearest-neighbors + random sample of distant neighbors
Fine-tuning might double-check points with "too-large" force-gradient
and add some small number of careful long-distance springs that best reduce this.

- Approximating force-field would be generated server-side.
- Client drag-n-drop uses approx force field (perhaps with some expanded *user dims*)
- State is preserved after rerunning umap? Or is it better to save the spring model
  and let the user decide when to run a full UMAP recalc (with new drag constraints etc.)

Shorter distance ~ higher spring constant; longer ~ weak spring constants

### drag-n-drop & high-D embedding
The current approach embeds high-D euclidean to low-D euclidean.  However, the drag'n'drop *user interest* was generated from a single high-D feature.

#### What rotation of high-D space, when projected onto the first 2 dims, best matches the dragged points?
- i.e. align 1st PCA component of the dragged point data with x axis.
   - 2nd one would be some randomish projection (ok, user doesn't really care about *y* yet,
     except that it should yield "some" separation in lo-D space
- a weighted-Euclidean metric (in the rotated hi-D space) might work nicely.
- but no dims should get *zero* weight
   - to avoid catastropic info loss
   - so 'y' axis still allows separation of individual items
   - (do not want all items to appear on single left-right line

In [1]:
from bokeh.plotting import figure, output_file, show
from bokeh.models import CategoricalColorMapper, ColumnDataSource, HoverTool
from bokeh.palettes import Category10, Colorblind, Viridis
from bokeh.io import output_notebook
from bokeh.layouts import column
output_notebook()

import umap
import numpy as np
from sklearn.datasets import load_iris
import pandas as pd

Loading BokehJS ...

In [2]:
import umap
#umap.constraints.test_HardPinIndexed()
#umap.constraints.test_SoftPinIndexed()
umap.constraints.test_DimLohi()


test_DimLohi seems OK


In [3]:
iris = load_iris()

In [4]:
print(type(iris))
print(type(iris.data))
print(iris.data.shape, iris.data[0:5,])
print(iris.target.shape, iris.target[0:5])
print(iris.target_names.size, iris.target_names)
print(len(iris.feature_names), iris.feature_names)

<class 'sklearn.utils.Bunch'>
<class 'numpy.ndarray'>
(150, 4) [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
(150,) [0 0 0 0 0]
3 ['setosa' 'versicolor' 'virginica']
4 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
# I'm interested in feature 0 (sepal length) really small.
feature_of_interest = 0
fi_name = iris.feature_names[feature_of_interest]
di = data_of_interest = iris.data[:,feature_of_interest]
if True:
    # This time, choose good/bad from each iris species
    nFeat = iris.target_names.size
    good10 = np.zeros(nFeat,dtype=np.int32)
    bad10 = np.zeros(nFeat,dtype=np.int32)
    for t,name in enumerate(iris.target_names):
        print(t,name)
        mask = (iris.target==t)
        #print(di[mask])
        dilo = np.argmin(di[mask]) # index within masked group
        dihi = np.argmax(di[mask])
        #print(dilo)
        diilo = np.arange(di.shape[0]) [mask] [dilo] # index within original
        diihi = np.arange(di.shape[0]) [mask] [dihi]
        #print(diilo)
        good10[t] = diilo
        bad10[t] = diihi

    print("\nSelected shortest (good) and longest (bad)",
          fi_name, "of each iris species")
    print(fi_name, "good/bad values:")
    row_names = ["good", "bad"]
    col_names = iris.target_names
    matrix = np.zeros((2,3))
    for t,name in enumerate(col_names):
        matrix[0,t] = iris.data[ good10[t], feature_of_interest ]
        matrix[1,t] = iris.data[ bad10[t], feature_of_interest ]
    df = pd.DataFrame(matrix, columns=col_names, index=row_names)
    print(df)
    print("\n")
    

if False: # older case
    # choose 2 "interesting" examples and 2 uninteresting
    nFeat = 4
    print("feature_of_interest",feature_of_interest)
    best = np.argmin(data_of_interest)
    #good3 = np.argpartition(iris.data[:,0], 3)
    #print("good",good, "good3",good3)
    #print(iris.data[good3,])
    goods = np.argsort(data_of_interest)
    good10 = goods[0:nFeat]
    bad10 = goods[-nFeat:,]

print("good10",good10,"\ndata of goods:\n",iris.data[good10,])
print("bad10",bad10,  "\ndata of bads:\n",iris.data[bad10])
#

0 setosa
1 versicolor
2 virginica

Selected shortest (good) and longest (bad) sepal length (cm) of each iris species
sepal length (cm) good/bad values:
      setosa  versicolor  virginica
good     4.3         4.9        4.9
bad      5.8         7.0        7.9


good10 [ 13  57 106] 
data of goods:
 [[4.3 3.  1.1 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]
bad10 [ 14  50 131] 
data of bads:
 [[5.8 4.  1.2 0.2]
 [7.  3.2 4.7 1.4]
 [7.9 3.8 6.4 2. ]]


In [6]:
##%%writefile iris4-emb-init.log
##%%capture iris4-emb-init.log
embedding = umap.UMAP(
    n_neighbors=50, learning_rate=0.5, random_state=12345, init="random", min_dist=0.001
).fit_transform(iris.data)
print(embedding[0:15,])

[[-1.7215905 14.415081 ]
 [-2.3275075 13.216359 ]
 [-1.7560098 13.077794 ]
 [-2.0715408 12.843264 ]
 [-1.6447545 14.243146 ]
 [-1.0182917 14.778511 ]
 [-1.8471808 13.001267 ]
 [-1.7536619 13.881872 ]
 [-2.023358  12.600967 ]
 [-2.2560585 13.025465 ]
 [-1.3089044 14.793785 ]
 [-1.8042557 13.558329 ]
 [-2.211919  12.999029 ]
 [-1.9863918 12.630116 ]
 [-1.1587598 14.963011 ]]


In [7]:
print(embedding[0:15,])

[[-1.7215905 14.415081 ]
 [-2.3275075 13.216359 ]
 [-1.7560098 13.077794 ]
 [-2.0715408 12.843264 ]
 [-1.6447545 14.243146 ]
 [-1.0182917 14.778511 ]
 [-1.8471808 13.001267 ]
 [-1.7536619 13.881872 ]
 [-2.023358  12.600967 ]
 [-2.2560585 13.025465 ]
 [-1.3089044 14.793785 ]
 [-1.8042557 13.558329 ]
 [-2.211919  12.999029 ]
 [-1.9863918 12.630116 ]
 [-1.1587598 14.963011 ]]


In [8]:
#output_file("iris2a.html")

targets = [str(d) for d in iris.target_names]
targets += ["good","bad"]
source = ColumnDataSource(
    data = dict(
        x0=embedding[:,0],
        y0=embedding[:,1],
        #g=[i in good10 for e,i in enumerate(embedding) # ?
        #b=[i in bad10  for i in range(embedding.shape[0])] # equiv for bad ?
        label=[targets[d] for d in iris.target],
    )
)
#for i in range(len(iris.feature_names)
#    source.data[iris.feature_names[i]] = iris.data[i,]
# 4 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
source.data["Sepal_Length"] = iris.data[:,0]
source.data["Sepal_Width"]  = iris.data[:,1]
source.data["Petal_Length"] = iris.data[:,2]
source.data["Petal_Width"]  = iris.data[:,3]
tooltips = [
    ("(x,y)",  "(@x0,@y0)"),   # tooltips[1] can be modified in later plots
    ("Iris Sample", "$index: @label"),
    ("Sepal Length,Width", "@Sepal_Length{0.0}, @Sepal_Width{0.0}"),
    ("Petal Length,Width", "@Petal_Length{0.0}, @Petal_Width{0.0}"),
]
#print(tooltips[0])

cmap = CategoricalColorMapper(factors=targets, palette=Category10[10])

p1 = figure(title="Test UMAP on Iris dataset",
            tooltips=tooltips)
circles = p1.circle(source=source, x="x0", y="y0",
    size=8, fill_alpha=0.5,
    color={"field": "label", "transform": cmap},
    #legend_label="species",
    legend_group="label"
)
# tooltips are only for circles
hover = p1.select_one(HoverTool)
hover.renderers = [circles]

# gray boxes around good/bad points and (fake) category
gb = np.vstack([embedding[good10,], embedding[bad10,]])
gbcat = np.hstack((np.repeat("good",nFeat), np.repeat("bad",nFeat)))
gbsource = ColumnDataSource( dict(
        x0 = gb[:,0],
        y0 = gb[:,1],
        label = gbcat,
    ))
p1.square(source=gbsource, x="x0", y="y0",
          size=16, line_alpha=0.7, line_width=4, fill_alpha=0.0,
          color={"field": "label", "transform": cmap},
          legend_group="label",
)
#p1.add_layout(p1.legend[0], 'right') # outside, plot rectangular!
#p1.legend.location = 'top_left'
#p1.legend.location = 'top_right'
p1.legend.location = 'center_center'

show(p1)

In [9]:
print("good10:\n", embedding[good10,])
print("bad10:\n",  embedding[bad10,])

good10:
 [[-1.9863918 12.630116 ]
 [-1.4760946  2.0882485]
 [-0.6749456  2.0352402]]
bad10:
 [[-1.1587598 14.963011 ]
 [ 1.0189372  3.3138897]
 [ 3.896607   3.294853 ]]


In [10]:
# simulate drag'n'drop of goods to left, bads to right

print("good10:\n",  embedding[good10,])
print("bad10:\n",   embedding[bad10,])# simulate drag'n'drop of goods to left, bads to right
method_names=["force", "linear", "rot,scale,trans"]
method=2
#
# method 1: "best" linear transform of x-coords of embedding
#
# y = [e 1] @ [m c] st. e'[good10,][0] ~ -1 and e'[bad10,][0] ~ 1
def emb_linear(emb0, emb1, pt0, pt1, coord=0 ):
    """ shift emb0, emb1 towards goals t0, t1 returning mx+c that best shifts x (axis=0) values """
    e = np.hstack((emb0[:,coord], emb1[:,coord]))
    # hoping for first half ~ -1, rest ~ +1
    y = np.hstack((np.repeat(pt0[coord],emb0.shape[0]), np.repeat(pt1[coord],emb1.shape[0])))
    print(type(e), type(y), e.shape, y.shape)
    assert( e.size == y.size )
    A = np.vstack([e, np.ones(len(e))]).T  # add a one's column
    print(type(A), A.shape, "\n")
    print("A", A)
    print("y", y)

    #x, residuals, rank, s = np.linalg.lstsq(A, y, rcond=None)
    #print("lstsq -> x=",x)
    #m,c = x
    m,c = np.linalg.lstsq(A, y, rcond=None)[0]
    print("m,c",np.round(m,3),np.round(c,3))
    print("fit",m*e+c)
    return [m, c]

def emb_linear_apply(x, embedding):
    m = x[0]
    c = x[1]
    emb2 = embedding
    # re-embed all data w/ "best" linear transform of 'x' values
    # rescale 'y' too, (keep rel. distances, don't care about y shift)
    emb2[:,0] = m * embedding[:,0] + c
    emb2[:,1] = m * embedding[:,1]
    emb2[:,1] -= np.average(emb2, axis=1) # 'y' centroid --> zeroprint("good10:\n", embedding[good10,])
    return embedding

def opa(a, b):
    """ return rot, scale, translation, and rmsd of shifting `b` to concord with `a`.
    
    `a` and `b` are N D-dim vectors.
    
    Suppose we return r, s, t, d.
    
    To apply the recovered transform to other M D-dim vectors X, calculate
    `X.dot(r) * s + t`
    """
    assert( a.shape == b.shape )
    aT = a.mean(0)
    bT = b.mean(0)
    A = a - aT 
    B = b - bT
    aS = np.sum(A * A)**.5
    bS = np.sum(B * B)**.5
    A /= aS
    B /= bS
    U, _, V = np.linalg.svd(np.dot(B.T, A))
    aR = np.dot(U, V)
    if np.linalg.det(aR) < 0:
        V[1] *= -1
        aR = np.dot(U, V)
    aS = aS / bS
    aT-= (bT.dot(aR) * aS)
    # the original only returned a rotation-only "rms"... between scaled+translated points
    aD = (np.sum((A - B.dot(aR))**2) / len(a))**.5
    # the xform in general is : a[1] = a[1].dot(r) * s + t
    # if we actually DO the full transform "LONG HAND"
    #aD = np.sqrt(((a - (b.dot(aR) * aS + aT))**2).sum() / len(a))
    # equivalently, include scaling into previous rmsd as
    aD *= (aS * bS)
    return aR, aS, aT, aD 
        
def emb_opa(emb0, emb1, pt0, pt1, coord=0):
    """ rotate,scale,translate s.t. coord of emb0,emb1 somewhat match 2 points pt0,pt1."""
    print(len(pt0), emb0.shape)
    D = emb0.shape[1]
    assert( len(pt0) == D ) # emb0 and pt0 are both D-dim
    assert( emb1.shape[1] == D )
    assert( len(pt1) == D )
    e = np.vstack((emb0, emb1))
    print(e.shape, e)
    # hoping for first half ~ -1, rest ~ +1
    # if pt0,pt1 were scalar target values for a single coord...
    #y = np.zeros_like(e)
    #y[:,coord] = np.hstack((np.repeat(pt0,emb0.shape[0]), np.repeat(pt1,emb1.shape[0])))
    #print("y[,feat]",y[:,feature_of_interest])
    # if pt0,pt1 are D-dim target points for each class emb0/emb1
    y = np.repeat( np.vstack((pt0,pt1)), [emb0.shape[0],emb1.shape[0]], axis=0 )
    print(y.shape, y)
    
    print(type(e), type(y), e.shape, y.shape)
    assert( e.size == y.size )
    #r,s,t,d = opa(y,e)
    return opa(y,e)
def emb_opa_apply(x, embedding):
    """ given x=[r,s,t,d]"""
    return embedding.dot(x[0]) * x[1] + x[2]

#
# method 0: naive, brute force
#
if method==0:
    emb2 = embedding
    emb2[good10,0] = -10.0
    emb2[bad10,0] = +10.0
    # --- without clamping, we totally lose the "init" state

#
# method 1: "best" linear transform of x-coords of embedding
#
if method==1:
    print("good10:\n",  embedding[good10,])
    print("bad10:\n",  embedding[bad10,])
    x = emb_linear( embedding[good10,], embedding[bad10,], [-10,0], [10,0] )
    print("x", x)
    emb2 = emb_linear_apply( x, embedding)

#
# method 2: "best" rotate, scale and translate
#
if method==2:
    x = emb_opa( embedding[good10,], embedding[bad10,], [-10,0], [10,0] )
    print("x", x)
    emb2 = emb_opa_apply( x, embedding)

print("UMAP pinning init method", method_names[method])
print("emb2 pinning init good10:\n",  emb2[good10,])
print("emb2 pinning init bad10:\n",  emb2[bad10,])
#embedding = emb2

good10:
 [[-1.9863918 12.630116 ]
 [-1.4760946  2.0882485]
 [-0.6749456  2.0352402]]
bad10:
 [[-1.1587598 14.963011 ]
 [ 1.0189372  3.3138897]
 [ 3.896607   3.294853 ]]
2 (3, 2)
(6, 2) [[-1.9863918 12.630116 ]
 [-1.4760946  2.0882485]
 [-0.6749456  2.0352402]
 [-1.1587598 14.963011 ]
 [ 1.0189372  3.3138897]
 [ 3.896607   3.294853 ]]
(6, 2) [[-10   0]
 [-10   0]
 [-10   0]
 [ 10   0]
 [ 10   0]
 [ 10   0]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'> (6, 2) (6, 2)
x (array([[ 0.8535749 , -0.52097015],
       [ 0.52097015,  0.8535749 ]]), 1.7628733766923537, array([-5.77090007, -9.66991021]), 12.068721716017658)
UMAP pinning init method rot,scale,trans
emb2 pinning init good10:
 [[ 2.83964241 11.15949857]
 [-6.07418865 -5.17197807]
 [-4.91734719 -5.98752082]]
emb2 pinning init bad10:
 [[ 6.22755742 13.90980757]
 [-1.194169   -5.6191494 ]
 [ 3.11850509 -8.29065938]]


In [11]:
#plot emb2
# Modify existing ColumnDataSources
source.data["x2"] = emb2[:,0]
source.data["y2"] = emb2[:,1]
tooltips[0] = ("(x,y)",  "(@x2,@y2)")
# gray boxes around good/bad points and (fake) category
gb = np.vstack([emb2[good10,], emb2[bad10,]])
gbsource.data["x2"] = gb[:,0]
gbsource.data["y2"] = gb[:,1]
#print(tooltips)
#cmap = CategoricalColorMapper(factors=targets, palette=Category10[10])

p2 = figure(title=("Iris "+method_names[method]+" drag'n'drop init"),
            tooltips=tooltips
           )
circles = p2.circle( source=source, x="x2", y="y2",
    size=8, fill_alpha=0.5,
    color={"field": "label", "transform": cmap},
    legend_group="label"
)
hover = p2.select_one(HoverTool)
hover.renderers = [circles]

p2.square(source=gbsource, x="x2", y="y2",
          size=16, line_alpha=0.7, line_width=4, fill_alpha=0.0,
          color={"field": "label", "transform": cmap},
          legend_group="label"
)
#p2.legend.location = 'top_right'
#p2.legend.location = 'top_left'
p2.legend.location = 'center_center'
show(p2)

In [12]:
# Pinned UMAP (and undo UMAP internal rescaling)
emb3 = emb2.copy()
emb3[good10,0] = -10
emb3[bad10,0]  = +10
print("embedding.shape",emb3.shape)
print("good10:\n", emb3[good10,])
print("bad10:\n",  emb3[bad10,])# re-embed just with new init conditions
pin_mask = np.ones(emb3.shape, dtype=np.float32) # todo: allow float32
pin_mask[good10,0] = 0.0 # zero gradient, so zero 'x' movement of init embedding
pin_mask[bad10,0] = 0.0
for i in range(pin_mask.shape[0]):
    if np.any(pin_mask[i,] == 0.0):
        print("pinned sample",i,"pin_mask",pin_mask[i,],"emb3",emb3[i,])
print("pin_mask.shape",pin_mask.shape)
print("pin_mask good10:\n", pin_mask[good10,])
print("pin_mask bad10:\n",  pin_mask[bad10,])# re-embed just with new init conditions
#   NOTE: should have pin_mask in UMAP constructor !

embedding.shape (150, 2)
good10:
 [[-10.          11.15949857]
 [-10.          -5.17197807]
 [-10.          -5.98752082]]
bad10:
 [[10.         13.90980757]
 [10.         -5.6191494 ]
 [10.         -8.29065938]]
pinned sample 13 pin_mask [0. 1.] emb3 [-10.          11.15949857]
pinned sample 14 pin_mask [0. 1.] emb3 [10.         13.90980757]
pinned sample 50 pin_mask [0. 1.] emb3 [10.        -5.6191494]
pinned sample 57 pin_mask [0. 1.] emb3 [-10.          -5.17197807]
pinned sample 106 pin_mask [0. 1.] emb3 [-10.          -5.98752082]
pinned sample 131 pin_mask [0. 1.] emb3 [10.         -8.29065938]
pin_mask.shape (150, 2)
pin_mask good10:
 [[0. 1.]
 [0. 1.]
 [0. 1.]]
pin_mask bad10:
 [[0. 1.]
 [0. 1.]
 [0. 1.]]


In [13]:
##%%writefile iris4-reemb.log
print("init=emb3 good10:\n", emb3[good10,])
print("init=emb3 bad10:\n",  emb3[bad10,])# re-embed just with new init conditions
embedder = umap.UMAP(
    n_neighbors=50, learning_rate=0.5, random_state=12346, init=emb3,
    negative_sample_rate=5, repulsion_strength=0.40,
    min_dist=0.001, spread=3.0,
    #a=0.1, b=0.9,
)
emb3 = embedder.fit_transform(iris.data, pin_mask=pin_mask)
print(emb3[0:15,])
print("pinned umap emb3 good10:\n", emb3[good10,])
print("pinned umap emb3 bad10:\n",  emb3[bad10,])

init=emb3 good10:
 [[-10.          11.15949857]
 [-10.          -5.17197807]
 [-10.          -5.98752082]]
init=emb3 bad10:
 [[10.         13.90980757]
 [10.         -5.6191494 ]
 [10.         -8.29065938]]
X.shape (150, 4)
pin_mask.shape (150, 2)
TRIAL: opt+mask+version 1
sample 13 pin head[ 0 ] begins at -10.0
sample 14 pin head[ 0 ] begins at 10.0
sample 50 pin head[ 0 ] begins at 10.0
sample 57 pin head[ 0 ] begins at -10.0
sample 106 pin head[ 0 ] begins at -10.0
sample 131 pin head[ 0 ] begins at 10.0
[[-1.1148797  17.563055  ]
 [-3.3702517  18.104368  ]
 [-3.5277183  17.169365  ]
 [-3.6953256  17.607618  ]
 [-1.2264082  17.499573  ]
 [ 0.13984221 18.136782  ]
 [-3.2134898  17.032341  ]
 [-1.8561774  17.363214  ]
 [-4.100444   17.48821   ]
 [-3.083722   17.895575  ]
 [-0.10179099 17.589872  ]
 [-2.4700067  17.652836  ]
 [-3.5898151  17.923103  ]
 [-5.         17.35616   ]
 [ 5.         17.75209   ]]
pinned umap emb3 good10:
 [[-5.        17.35616  ]
 [-5.        -5.0531383]
 [-5.

In [14]:
# UMAP has rescaled things "behind our back".
# I modified UMAP to avoid the rescale if pin_mask is not None
#    (or maybe if "enough" points have been pinned?)
# There were also mods needed to avoid dimension-wise rescaling
#    factors begin applied during 'init='
print("pinned umap good10:\n", emb3[good10,])
print("pinned umap bad10:\n",  emb3[bad10,])

emb4 = emb3.copy()
if False: # old code (this coord-rescale method is actually what we want to do.)
    # Oh-oh.  umap is doing some internal rescaling -- let's undo that.
    goodx = emb3[good10[0],0]
    badx  = emb3[bad10[0],0]
    print("umap --> good,bad=",goodx,badx)
    x = np.array([goodx,badx])
    A = np.array([[goodx,1.0],[badx,1.0]])
    y = np.array([-1.0,1.0])
    print("A\n",A,"\ny\n",y)
    m, c = np.linalg.lstsq(A, y, rcond=None)[0]
    print("m,c",np.round(m,3),np.round(c,3))
    print("fit",m*x+c)
    # scaling factor applies to BOTH x and y
    emb4[:,0] = m*emb3[:,0] + c
    emb4[:,1] = m*emb3[:,1]
    emb4[:,1] -= np.average(embedding, axis=1) # 'y' centroid --> zero

if False: # new: support several "re-project" methods
    # This reproject should ONLY SCALE
    rescale = 1
    if rescale==0:
        emb4[good10,0] = -10.0
        emb4[bad10,0] = +10.0
    if rescale==1: # use x-values to determine space scalings
        print("good10:\n",  emb3[good10,])
        print("bad10:\n",  emb3[bad10,])
        x = emb_linear( emb3[good10,], emb3[bad10,], [-10,0], [10,0] )
        print("x", x)
        emb4 = emb_linear_apply( x, emb3)
    if rescale==2:
        # rotate/scale/translate WILL NOT RE-PIN the x-values as desired!
        x = emb_opa( emb3[good10,], emb3[bad10,], [-10,0], [10,0] )
        print("x", x)
        emb4 = emb_opa_apply( x, emb3)
print("re-shift good10:\n", emb4[good10,])
print("re-shift bad10:\n",  emb4[bad10,])

pinned umap good10:
 [[-5.        17.35616  ]
 [-5.        -5.0531383]
 [-5.        -5.979412 ]]
pinned umap bad10:
 [[ 5.        17.75209  ]
 [ 5.        -3.6708148]
 [ 5.        -5.123134 ]]
re-shift good10:
 [[-5.        17.35616  ]
 [-5.        -5.0531383]
 [-5.        -5.979412 ]]
re-shift bad10:
 [[ 5.        17.75209  ]
 [ 5.        -3.6708148]
 [ 5.        -5.123134 ]]


In [15]:
#output_file("iris4.html")

source.data["x4"] = emb4[:,0]
source.data["y4"] = emb4[:,1]
tooltips[0] = ("(x,y)",  "(@x4,@y4)")
# gray boxes around good-bad (fake) drag'n'drop "category"
gb = np.vstack([emb4[good10,], emb4[bad10,]])
gbsource.data["x4"] = gb[:,0]
gbsource.data["y4"] = gb[:,1]

p4 = figure(title="Iris UMAP post drag'n'drop",
            tooltips=tooltips)
circles = p4.circle( source=source, x="x4", y="y4",
    size=8, fill_alpha=0.5,
    color={"field": "label", "transform": cmap},
    legend_group="label"
)
hover = p4.select_one(HoverTool)
hover.renderers = [circles]
p4.square(source=gbsource, x="x4", y="y4",
          size=16, line_alpha=0.7, line_width=4, fill_alpha=0.0,
          color={"field": "label", "transform": cmap},
          legend_group="label"
)
p4.legend.location = 'center_center'


output_notebook()
show(p4)
output_file("iris4.html")
show(column(p1,p2,p4))

Loading BokehJS ...

In [16]:
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])
A = np.vstack([x, np.ones(len(x))]).T
print("A\n",A,"\ny\n",y)
m, c = np.linalg.lstsq(A, y, rcond=None)[0]
print("m,c",np.round(m,3),np.round(c,3))
print("fit",m*x+c)

A
 [[0. 1.]
 [1. 1.]
 [2. 1.]
 [3. 1.]] 
y
 [-1.   0.2  0.9  2.1]
m,c 1.0 -0.95
fit [-0.95  0.05  1.05  2.05]


In [17]:
a=[1,2,3]; a+=[4,5]; print(a)
a=np.array([1,2,3]); a = np.hstack((a, [4,5])); print(a)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [18]:
# test @jitclass for a "constraint" example
import numba
from numba.experimental import jitclass

dimLohiSpec = [
    ('lo',  numba.types.float32[:]),
    ('hi',  numba.types.float32[:]),
    #('size',numba.types.int32),
]

@jitclass(dimLohiSpec)
class DimLohi(object):
    def __init__(self, lo, hi):
        """ clip dim[i] to range lo[i]..hi[i], for i with lo[i] < hi[i];
            o/w clip to [-10.0,+10.0]
        """
        if self.lo.size != self.hi.size:
            print("warning: DimLohi(lo[],hi[]) lo and hi vectors should have same size")
        #self.size = min(lo.size, hi.size)    
        sz = min(lo.size, hi.size)    
        self.lo = lo[0:sz]
        self.hi = hi[0:sz]
        for i in range(self.lo.size):
            #print("cmp",self.lo[i], self.hi[i])
            if self.lo[i] >= self.hi[i]:
                self.lo[i] = -10.0
                self.hi[i] = +10.0
        #print("DimLohi lo",self.lo)
        #print("DimLohi hi",self.hi)

    #@property
    #def size(self):
    #    return self.lo.size
    
    #@numba.jit(numba.types.float32[:](numba.typeof(dimLohiSpec), numba.types.float32[:]))
    # --> "class members not yet supported"
    def project_onto_constraint(self, vec):
        """ In-place bounding of vec[] dimension-wise """
        if len(vec.shape) == 1 and vec.shape[0] >= self.lo.size:
            for i in range(self.lo.size):
                #print("cmp",self.lo[i], vec[i], self.hi[i])
                if   vec[i] < self.lo[i]:
                     vec[i] = self.lo[i]
                elif vec[i] > self.hi[i]:
                     vec[i] = self.hi[i]
        else:
            print("Mismatch between vec shape",vec.shape,"with DimLohi size", self.lo.size)
        return vec

    def project_rows_onto_constraint(self, mat):
        """ In-place bounding of mat[i,dim] dimension-wise """
        if len(mat.shape) == 2 and mat.shape[1] >= self.lo.size:
            for i in range(mat.shape[0]):
                for j in range(self.lo.size):
                    #print("cmp",self.lo[i], vec[i], self.hi[i])
                    if   mat[i,j] < self.lo[j]:
                         mat[i,j] = self.lo[j]
                    elif mat[i,j] > self.hi[j]:
                         mat[i,j] = self.hi[j]
        else:
            print("Mismatch between mat shape",mat.shape,"with DimLohi size", self.lo.size)
        return mat

# Try it out with 8 samples, each with 5 dims
#        bound the first 3 dims, not the rest.
#bd = DimLohi([-0.25, -0.5, -0.75, -0.5, -0.5], [+0.25, +0.5, +0.75, -1,   -1])
# no... need exactly-matching types for constructor

lows = np.array([-0.25, -0.5, -0.75, -0.5, -0.5],dtype=np.float32)
higs = np.array([+0.25, +0.5, +0.75, -1,   -1],dtype=np.float32)
print("lows\n",lows)
print("higs\n",higs)
print(numba.typeof(lows))
bd = DimLohi(lows, higs)

a = np.floor((np.random.rand(8,5)*2-1) * 100) * 0.01
print("a[2]=",a[2],"shape",a[2].shape)
assert( a[2].shape == (5,))

b = a.copy()
for i in range(b.shape[0]):
    bd.project_onto_constraint(b[i,])
print("a\n",a)
print("b\n",b)

# perhaps slightly slower way to generate b without modifying a
for i in range(a.shape[0]):
    b[i,] = bd.project_onto_constraint(a[i,].copy())
print("a\n",a)
print("b\n",b)

b = a.copy()
bd.project_rows_onto_constraint(b)
print("bd.project_rows_onto_constraint(b)\n",b)


lows
 [-0.25 -0.5  -0.75 -0.5  -0.5 ]
higs
 [ 0.25  0.5   0.75 -1.   -1.  ]
array(float32, 1d, C)
a[2]= [ 0.12 -0.28 -0.02  0.31  0.42] shape (5,)
a
 [[-0.64  0.73 -0.89 -0.43  0.54]
 [ 0.36 -0.07 -0.18  0.4   0.3 ]
 [ 0.12 -0.28 -0.02  0.31  0.42]
 [-0.31 -0.51 -0.56 -0.05  0.53]
 [-0.87  0.23 -0.26 -0.64 -0.67]
 [-0.33 -0.62 -0.93  0.28  0.06]
 [ 0.76 -0.7   0.99 -0.51  0.12]
 [ 0.45  0.19  0.66 -0.39 -0.31]]
b
 [[-0.25  0.5  -0.75 -0.43  0.54]
 [ 0.25 -0.07 -0.18  0.4   0.3 ]
 [ 0.12 -0.28 -0.02  0.31  0.42]
 [-0.25 -0.5  -0.56 -0.05  0.53]
 [-0.25  0.23 -0.26 -0.64 -0.67]
 [-0.25 -0.5  -0.75  0.28  0.06]
 [ 0.25 -0.5   0.75 -0.51  0.12]
 [ 0.25  0.19  0.66 -0.39 -0.31]]
a
 [[-0.64  0.73 -0.89 -0.43  0.54]
 [ 0.36 -0.07 -0.18  0.4   0.3 ]
 [ 0.12 -0.28 -0.02  0.31  0.42]
 [-0.31 -0.51 -0.56 -0.05  0.53]
 [-0.87  0.23 -0.26 -0.64 -0.67]
 [-0.33 -0.62 -0.93  0.28  0.06]
 [ 0.76 -0.7   0.99 -0.51  0.12]
 [ 0.45  0.19  0.66 -0.39 -0.31]]
b
 [[-0.25  0.5  -0.75 -0.43  0.54]
 [ 0.25 -0.07

In [19]:
#constrain_lo = np.float32(-10.0)
#constrain_hi = np.float32(+10.0)
from umap.constraints import constrain_lo, constrain_hi
#constrain_lo = -1.0
#constrain_hi = +1.0
a = np.arange(9)
a = a.reshape((3,3))
print(a.shape,"\n",a)
a[[0,2],:] = [[1,1,1],[2,2,2]]
print(a)
b = np.arange(10)
np.random.shuffle(b)
print(b)
dups = np.any(np.diff(np.sort(b))==0)
print(dups)
b[0] = b[-1]
print(b)
dups = np.any(np.diff(np.sort(b))==0)
print(dups)
s = np.sort(b, axis=None)
print(s[1:])
print(s[:-1])
s[:-1][s[1:] == s[:-1]]

(3, 3) 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 1 1]
 [3 4 5]
 [2 2 2]]
[4 8 6 0 1 5 7 9 2 3]
False
[3 8 6 0 1 5 7 9 2 3]
True
[1 2 3 3 5 6 7 8 9]
[0 1 2 3 3 5 6 7 8]


array([3])

In [20]:
# here is the umap 'euclidean output' rescaling factor
lo = np.min(embedding,0)
spread = np.max(embedding,0) - np.min(embedding,0)
print("lo",lo)
print("spread",spread)
emb2x = 10.0 * (emb2 - lo) / (spread)
print("emb2\n",emb2[0:15,])
print("emb2x\n",emb2x[0:15,])

lo [-2.393327  1.726808]
spread [ 6.478792 13.248088]
emb2
 [[ 4.87741996 13.60221947]
 [ 2.86475829 12.35492616]
 [ 3.59745749 11.62155517]
 [ 2.90727015 11.55843185]
 [ 4.83513255 13.27293459]
 [ 6.26948067 13.50317606]
 [ 3.38998599 11.590134  ]
 [ 4.33945942 12.82933088]
 [ 2.75724692 11.14958673]
 [ 2.79695283 12.00206017]
 [ 5.84621058 13.79305958]
 [ 3.96618478 12.38894613]
 [ 2.83909252 11.92174316]
 [ 2.83964241 11.15949857]
 [ 6.22755742 13.90980757]]
emb2x
 [[11.22238025  8.96386831]
 [ 8.11584186  8.02237901]
 [ 9.2467613   7.46881158]
 [ 8.18145881  7.42116446]
 [11.15710975  8.71531556]
 [13.37102259  8.88910778]
 [ 8.92652954  7.44509407]
 [10.39203947  8.38047198]
 [ 7.94989833  7.11255757]
 [ 8.0111843   7.75602661]
 [12.71770623  9.10791938]
 [ 9.81589097  8.04805816]
 [ 8.07622681  7.69540125]
 [ 8.07707557  7.12003929]
 [13.30631415  9.19604378]]


In [21]:
a = np.array([0., 1., np.inf, np.NAN, 4.])
print(np.isnan(a))
print(np.isinf(a))
b = np.array([0,1,2,3,4],dtype=np.float32)
print(-1,np.searchsorted(b,-1))
print(1,np.searchsorted(b,1))
print(1.5,np.searchsorted(b,1.5))
print(4,np.searchsorted(b,4))
print(4.01,np.searchsorted(b,4.01))
print(99,np.searchsorted(b,99))
b[4]
b[np.isinf(a)] += 0.1
b
s = np.sort(a)
print("s",type(s),s)

[False False False  True False]
[False False  True False False]
-1 0
1 1
1.5 2
4 4
4.01 5
99 5
s <class 'numpy.ndarray'> [ 0.  1.  4. inf nan]


In [22]:
np.array([0., 1., np.inf])
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.isnan(np.inf)
2 == np.inf
np.isscalar(2) # True
np.isscalar([2])
np.isscalar(np.float32(1.11)) # True
np.isscalar(np.array([1.11]))

False

In [24]:
a = np.broadcast_to(np.inf, (1,5))
print(a)
b = np.broadcast_to(a, (1,5))
print(b)
np.ndarray((1,5))

[[inf inf inf inf inf]]
[[inf inf inf inf inf]]


array([[inf, inf, inf, inf, inf]])

In [25]:
data = np.random.rand(5,3)
data = np.float32(data)
idx = np.array([1,3], dtype=np.int32)
pos = np.vstack( (np.repeat(0.,3), np.repeat(1.,3)) )
print(data)
print(idx)
print(pos)
print(data[idx,:])

[[0.2534551  0.06206123 0.9741958 ]
 [0.2298518  0.25978738 0.1362367 ]
 [0.4696666  0.59612465 0.75412035]
 [0.5157133  0.3147939  0.6822553 ]
 [0.09809946 0.08820195 0.71560097]]
[1 3]
[[0. 0. 0.]
 [1. 1. 1.]]
[[0.2298518  0.25978738 0.1362367 ]
 [0.5157133  0.3147939  0.6822553 ]]


In [26]:
np.ndarray( (5), dtype=np.float32)

array([0. , 1. , 2.1, 3. , 4. ], dtype=float32)

In [27]:
np.array()

TypeError: array() missing required argument 'object' (pos 1)